imports:
    - { resource: parameters.yml }

twig:
   globals:
       dash_version: "%cms_dash.version%"
       dash_name: "%cms_dash.name%"
       dash_charset: "%cms_dash.charset%"
       dash_author: "%cms_dash.author%"
       dash_description: "%cms_dash.description%"