imports:
    - { resource: parameters.yml }

twig:
   globals:
       dash_version: "%dash.version%"
       dash_name: "%dash.name%"
       dash_charset: "%dash.charset%"
       dash_author: "%dash.author%"
       dash_description: "%dash.description%"